apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-compose-imagestore-container
  name: spring-compose-imagestore-container
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spring-compose-imagestore-container
    spec:
      containers:
      - image: guthedar/spring-imagestore:latest
        name: spring-compose-imagestore-container
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data/spring-imagestore
          name: spring-compose-imagestore-container-claim0
      restartPolicy: Always
      volumes:
      - name: spring-compose-imagestore-container-claim0
        persistentVolumeClaim:
          claimName: spring-compose-imagestore-container-claim0
status: {}
